// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`hu`] = []string{
		`---`,
		`jan.`,
		`febr.`,
		`márc.`,
		`ápr.`,
		`máj.`,
		`jún.`,
		`júl.`,
		`aug.`,
		`szept.`,
		`okt.`,
		`nov.`,
		`dec.`,
	}

	LongMonthNames[`hu`] = []string{
		`---`,
		`január`,
		`február`,
		`március`,
		`április`,
		`május`,
		`június`,
		`július`,
		`augusztus`,
		`szeptember`,
		`október`,
		`november`,
		`december`,
	}

	ShortWeekdays[`hu`] = []string{
		`V`,
		`H`,
		`K`,
		`Sze`,
		`Cs`,
		`P`,
		`Szo`,
	}

	LongWeekdays[`hu`] = []string{
		`vasárnap`,
		`hétfő`,
		`kedd`,
		`szerda`,
		`csütörtök`,
		`péntek`,
		`szombat`,
	}

}
