// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`nl`] = []string{
		`---`,
		`jan.`,
		`feb.`,
		`mrt.`,
		`apr.`,
		`mei`,
		`jun.`,
		`jul.`,
		`aug.`,
		`sep.`,
		`okt.`,
		`nov.`,
		`dec.`,
	}

	LongMonthNames[`nl`] = []string{
		`---`,
		`januari`,
		`februari`,
		`maart`,
		`april`,
		`mei`,
		`juni`,
		`juli`,
		`augustus`,
		`september`,
		`oktober`,
		`november`,
		`december`,
	}

	ShortWeekdays[`nl`] = []string{
		`zo`,
		`ma`,
		`di`,
		`wo`,
		`do`,
		`vr`,
		`za`,
	}

	LongWeekdays[`nl`] = []string{
		`zondag`,
		`maandag`,
		`dinsdag`,
		`woensdag`,
		`donderdag`,
		`vrijdag`,
		`zaterdag`,
	}

}
