// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`ro`] = []string{
		`---`,
		`ian.`,
		`feb.`,
		`mar.`,
		`apr.`,
		`mai`,
		`iun.`,
		`iul.`,
		`aug.`,
		`sept.`,
		`oct.`,
		`nov.`,
		`dec.`,
	}

	LongMonthNames[`ro`] = []string{
		`---`,
		`ianuarie`,
		`februarie`,
		`martie`,
		`aprilie`,
		`mai`,
		`iunie`,
		`iulie`,
		`august`,
		`septembrie`,
		`octombrie`,
		`noiembrie`,
		`decembrie`,
	}

	ShortWeekdays[`ro`] = []string{
		`Dum`,
		`Lun`,
		`Mar`,
		`Mie`,
		`Joi`,
		`Vin`,
		`Sâm`,
	}

	LongWeekdays[`ro`] = []string{
		`duminică`,
		`luni`,
		`marți`,
		`miercuri`,
		`joi`,
		`vineri`,
		`sâmbătă`,
	}

}
