// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`sv`] = []string{
		`---`,
		`jan.`,
		`feb.`,
		`mars`,
		`apr.`,
		`maj`,
		`juni`,
		`juli`,
		`aug.`,
		`sep.`,
		`okt.`,
		`nov.`,
		`dec.`,
	}

	LongMonthNames[`sv`] = []string{
		`---`,
		`januari`,
		`februari`,
		`mars`,
		`april`,
		`maj`,
		`juni`,
		`juli`,
		`augusti`,
		`september`,
		`oktober`,
		`november`,
		`december`,
	}

	ShortWeekdays[`sv`] = []string{
		`sön`,
		`mån`,
		`tis`,
		`ons`,
		`tors`,
		`fre`,
		`lör`,
	}

	LongWeekdays[`sv`] = []string{
		`söndag`,
		`måndag`,
		`tisdag`,
		`onsdag`,
		`torsdag`,
		`fredag`,
		`lördag`,
	}

}
