package extensions

import "os"

// These constants are to be used when you are passing an os.FileMode uint32 because it's easier to compose exactly what you want and gives you common directory that needs execute.
const (
	UNIX_READ        = 04
	UNIX_WRITE       = 02
	UNIX_EX          = 01
	UNIX_USER_SHIFT  = 6
	UNIX_GROUP_SHIFT = 3
	UNIX_OTH_SHIFT   = 0

	UNIX_USER_R   = UNIX_READ << UNIX_USER_SHIFT
	UNIX_USER_W   = UNIX_WRITE << UNIX_USER_SHIFT
	UNIX_USER_X   = UNIX_EX << UNIX_USER_SHIFT
	UNIX_USER_RW  = UNIX_USER_R | UNIX_USER_W
	UNIX_USER_RWX = UNIX_USER_RW | UNIX_USER_X

	UNIX_GROUP_R   = UNIX_READ << UNIX_GROUP_SHIFT
	UNIX_GROUP_W   = UNIX_WRITE << UNIX_GROUP_SHIFT
	UNIX_GROUP_X   = UNIX_EX << UNIX_GROUP_SHIFT
	UNIX_GROUP_RW  = UNIX_GROUP_R | UNIX_GROUP_W
	UNIX_GROUP_RWX = UNIX_GROUP_RW | UNIX_GROUP_X

	UNIX_OTH_R   = UNIX_READ << UNIX_OTH_SHIFT
	UNIX_OTH_W   = UNIX_WRITE << UNIX_OTH_SHIFT
	UNIX_OTH_X   = UNIX_EX << UNIX_OTH_SHIFT
	UNIX_OTH_RW  = UNIX_OTH_R | UNIX_OTH_W
	UNIX_OTH_RWX = UNIX_OTH_RW | UNIX_OTH_X

	UNIX_ALL_R       = UNIX_USER_R | UNIX_GROUP_R | UNIX_OTH_R
	UNIX_ALL_W       = UNIX_USER_W | UNIX_GROUP_W | UNIX_OTH_W
	UNIX_ALL_X       = UNIX_USER_X | UNIX_GROUP_X | UNIX_OTH_X
	UNIX_ALL_RW      = UNIX_ALL_R | UNIX_ALL_W
	UNIX_ALL_RWX     = UNIX_ALL_RW | UNIX_GROUP_X
	UNIX_COMMON_FILE = (UNIX_USER_RW | UNIX_ALL_R)
	UNIX_COMMON_DIR  = os.ModeDir | (UNIX_USER_RWX | UNIX_ALL_R)
	UNIX_DIR_RWALL   = os.ModeDir | (UNIX_USER_RWX | UNIX_ALL_RW)
)
