// AUTOGENERATED FROM CLDR DATA. DO NOT EDIT

package symbols

func init() {
	ShortMonthNames[`ko`] = []string{
		`---`,
		`1월`,
		`2월`,
		`3월`,
		`4월`,
		`5월`,
		`6월`,
		`7월`,
		`8월`,
		`9월`,
		`10월`,
		`11월`,
		`12월`,
	}

	LongMonthNames[`ko`] = []string{
		`---`,
		`1월`,
		`2월`,
		`3월`,
		`4월`,
		`5월`,
		`6월`,
		`7월`,
		`8월`,
		`9월`,
		`10월`,
		`11월`,
		`12월`,
	}

	ShortWeekdays[`ko`] = []string{
		`일`,
		`월`,
		`화`,
		`수`,
		`목`,
		`금`,
		`토`,
	}

	LongWeekdays[`ko`] = []string{
		`일요일`,
		`월요일`,
		`화요일`,
		`수요일`,
		`목요일`,
		`금요일`,
		`토요일`,
	}

}
