package controllers

const (
	//-DONT-REMOVE-NEW-CONST
	CONTROLLER_LOGS                      = "logs"
	CONTROLLER_FILEOBJECTADD             = "fileObjectAdd"
	CONTROLLER_FILEOBJECTLIST            = "fileObjectList"
	CONTROLLER_FILEOBJECTMODIFY          = "fileObjectModify"
	CONTROLLER_FILEOBJECTS               = "fileObjects"
	CONTROLLER_ROLEADD                   = "roleAdd"
	CONTROLLER_ROLELIST                  = "roleList"
	CONTROLLER_ROLEMODIFY                = "roleModify"
	CONTROLLER_ROLES                     = "roles"
	CONTROLLER_FILEUPLOAD                = "fileUpload"
	CONTROLLER_FEATUREGROUPADD           = "featureGroupAdd"
	CONTROLLER_FEATUREGROUPLIST          = "featureGroupList"
	CONTROLLER_FEATUREGROUPMODIFY        = "featureGroupModify"
	CONTROLLER_FEATUREGROUPS             = "featureGroups"
	CONTROLLER_ROLEFEATUREADD            = "roleFeatureAdd"
	CONTROLLER_ROLEFEATURELIST           = "roleFeatureList"
	CONTROLLER_ROLEFEATUREMODIFY         = "roleFeatureModify"
	CONTROLLER_ROLEFEATURES              = "roleFeatures"
	CONTROLLER_FEATUREADD                = "featureAdd"
	CONTROLLER_FEATURELIST               = "featureList"
	CONTROLLER_FEATUREMODIFY             = "featureModify"
	CONTROLLER_FEATURES                  = "features"
	CONTROLLER_APPERRORADD               = "appErrorAdd"
	CONTROLLER_APPERRORLIST              = "appErrorList"
	CONTROLLER_APPERRORMODIFY            = "appErrorModify"
	CONTROLLER_APPERRORS                 = "appErrors"
	CONTROLLER_TRANSACTIONADD            = "transactionAdd"
	CONTROLLER_TRANSACTIONLIST           = "transactionList"
	CONTROLLER_TRANSACTIONMODIFY         = "transactionModify"
	CONTROLLER_TRANSACTIONS              = "transactions"
	CONTROLLER_PASSWORDRESET             = "passwordReset"
	CONTROLLER_USERPROFILE               = "userProfile"
	CONTROLLER_USERADD                   = "userAdd"
	CONTROLLER_ACCOUNTADD                = "accountAdd"
	CONTROLLER_LOGIN                     = "login"
	CONTROLLER_HOME                      = "home"
	CONTROLLER_USERS                     = "users"
	CONTROLLER_SETTINGS                  = "settings"
	CONTROLLER_USERLIST                  = "userList"
	CONTROLLER_SERVERSETTINGSMODIFY      = "serverSettingsModify"
	CONTROLLER_USERMODIFY                = "userModify"
	CONTROLLER_ACCOUNTMODIFY             = "accountModify"
	CONTROLLER_ACCOUNTLIST               = "accountList"
	CONTROLLER_ACCOUNTS                  = "accounts"
	PARAM_SUCCESS                        = true
	PARAM_FAILED                         = false
	PARAM_REDIRECT_REFRESH               = "refresh"
	PARAM_REDIRECT_RERENDER              = "rerender"
	PARAM_REDIRECT_REFRESH_HOME          = "homeRefresh"
	PARAM_REDIRECT_BACK                  = "back"
	PARAM_REDIRECT_NONE                  = ""
	PARAM_SNACKBAR_MESSAGE_NONE          = ""
	PARAM_SNACKBAR_TYPE_SUCCESS          = ""
	PARAM_SNACKBAR_TYPE_WARNING          = "Warning"
	PARAM_SNACKBAR_TYPE_DOWNLOAD_CONTENT = "DownloadContent"
	PARAM_SNACKBAR_TYPE_DOWNLOAD_FILE    = "DownloadFile"
	PARAM_SNACKBAR_TYPE_ERROR            = "Error"
	PARAM_SNACKBAR_TYPE_ALERT            = "Alert"
	PARAM_SNACKBAR_TYPE_POPUP            = "Popup"
	PARAM_TRANSACTION_ID_NONE            = ""

	SCHEMA_ID_FIELD          = "Id"
	SCHEMA_USERS_EMAIL_FIELD = "Email"

	VALIDATION_INVALID_EMAIL  = "ValidationFieldSpecificEmailRequired"
	VALIDATION_REQUIRED_FIELD = "ValidationFieldSpecificRequired"

	SNACKBAR_TYPE_SUCCESS = ""
	SNACKBAR_TYPE_WARNING = "Warning"
	SNACKBAR_TYPE_ERROR   = "Error"

	//USER_MODIFY_PASSWORDMATCHFAIL = "PasswordMatch"
)
