language: go
go_import_path: github.com/HouzuoGuo/tiedot
sudo: false
go:
  - 1.4.3
  - 1.5.3
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
install:
  - go get github.com/dgrijalva/jwt-go
scritp:
 - go build
 - go test -v ./...