package viewModel

import (
	"encoding/json"
)

type RoutesViewModel struct {
	Paths struct {
		//-DONT-REMOVE-NEW-STRUCT
		CONTROLLER_LOGIN                string `json:"CONTROLLER_LOGIN"`
		CONTROLLER_HOME                 string `json:"CONTROLLER_HOME"`
		CONTROLLER_USERS                string `json:"CONTROLLER_USERS"`
		CONTROLLER_SETTINGS             string `json:"CONTROLLER_SETTINGS"`
		CONTROLLER_USERLIST             string `json:"CONTROLLER_USERLIST"`
		CONTROLLER_SERVERSETTINGSMODIFY string `json:"CONTROLLER_SERVERSETTINGSMODIFY"`
		CONTROLLER_USERMODIFY           string `json:"CONTROLLER_USERMODIFY"`
		CONTROLLER_ACCOUNTMODIFY        string `json:"CONTROLLER_ACCOUNTMODIFY"`
		CONTROLLER_ACCOUNTLIST          string `json:"CONTROLLER_ACCOUNTLIST"`
		CONTROLLER_ACCOUNTS             string `json:"CONTROLLER_ACCOUNTS"`
		CONTROLLER_FILEOBJECTADD        string `json:"CONTROLLER_FILEOBJECTADD"`
		CONTROLLER_FILEOBJECTLIST       string `json:"CONTROLLER_FILEOBJECTLIST"`
		CONTROLLER_FILEOBJECTMODIFY     string `json:"CONTROLLER_FILEOBJECTMODIFY"`
		CONTROLLER_FILEOBJECTS          string `json:"CONTROLLER_FILEOBJECTS"`
		CONTROLLER_ROLEADD              string `json:"CONTROLLER_ROLEADD"`
		CONTROLLER_ROLELIST             string `json:"CONTROLLER_ROLELIST"`
		CONTROLLER_ROLEMODIFY           string `json:"CONTROLLER_ROLEMODIFY"`
		CONTROLLER_ROLES                string `json:"CONTROLLER_ROLES"`
		CONTROLLER_FEATUREGROUPADD      string `json:"CONTROLLER_FEATUREGROUPADD"`
		CONTROLLER_FEATUREGROUPLIST     string `json:"CONTROLLER_FEATUREGROUPLIST"`
		CONTROLLER_FEATUREGROUPMODIFY   string `json:"CONTROLLER_FEATUREGROUPMODIFY"`
		CONTROLLER_FEATUREGROUPS        string `json:"CONTROLLER_FEATUREGROUPS"`
		CONTROLLER_ROLEFEATUREADD       string `json:"CONTROLLER_ROLEFEATUREADD"`
		CONTROLLER_ROLEFEATURELIST      string `json:"CONTROLLER_ROLEFEATURELIST"`
		CONTROLLER_ROLEFEATUREMODIFY    string `json:"CONTROLLER_ROLEFEATUREMODIFY"`
		CONTROLLER_ROLEFEATURES         string `json:"CONTROLLER_ROLEFEATURES"`
		CONTROLLER_FEATUREADD           string `json:"CONTROLLER_FEATUREADD"`
		CONTROLLER_FEATURELIST          string `json:"CONTROLLER_FEATURELIST"`
		CONTROLLER_FEATUREMODIFY        string `json:"CONTROLLER_FEATUREMODIFY"`
		CONTROLLER_FEATURES             string `json:"CONTROLLER_FEATURES"`
		CONTROLLER_APPERRORADD          string `json:"CONTROLLER_APPERRORADD"`
		CONTROLLER_APPERRORLIST         string `json:"CONTROLLER_APPERRORLIST"`
		CONTROLLER_APPERRORMODIFY       string `json:"CONTROLLER_APPERRORMODIFY"`
		CONTROLLER_APPERRORS            string `json:"CONTROLLER_APPERRORS"`
		CONTROLLER_TRANSACTIONADD       string `json:"CONTROLLER_TRANSACTIONADD"`
		CONTROLLER_TRANSACTIONLIST      string `json:"CONTROLLER_TRANSACTIONLIST"`
		CONTROLLER_TRANSACTIONMODIFY    string `json:"CONTROLLER_TRANSACTIONMODIFY"`
		CONTROLLER_TRANSACTIONS         string `json:"CONTROLLER_TRANSACTIONS"`
		CONTROLLER_PASSWORDRESET        string `json:"CONTROLLER_PASSWORDRESET"`
		CONTROLLER_USERPROFILE          string `json:"CONTROLLER_USERPROFILE"`
		CONTROLLER_USERADD              string `json:"CONTROLLER_USERADD"`
		CONTROLLER_ACCOUNTADD           string `json:"CONTROLLER_ACCOUNTADD"`
	} `json:"Paths"`
}

func (self *RoutesViewModel) LoadDefaultState() {
	//-DONT-REMOVE-NEW-SETTER
	self.Paths.CONTROLLER_FILEOBJECTADD = "fileObjectAdd"
	self.Paths.CONTROLLER_FILEOBJECTLIST = "fileObjectList"
	self.Paths.CONTROLLER_FILEOBJECTMODIFY = "fileObjectModify"
	self.Paths.CONTROLLER_FILEOBJECTS = "fileObjects"
	self.Paths.CONTROLLER_ROLEADD = "roleAdd"
	self.Paths.CONTROLLER_ROLELIST = "roleList"
	self.Paths.CONTROLLER_ROLEMODIFY = "roleModify"
	self.Paths.CONTROLLER_ROLES = "roles"
	self.Paths.CONTROLLER_FEATUREGROUPADD = "featureGroupAdd"
	self.Paths.CONTROLLER_FEATUREGROUPLIST = "featureGroupList"
	self.Paths.CONTROLLER_FEATUREGROUPMODIFY = "featureGroupModify"
	self.Paths.CONTROLLER_FEATUREGROUPS = "featureGroups"
	self.Paths.CONTROLLER_ROLEFEATUREADD = "roleFeatureAdd"
	self.Paths.CONTROLLER_ROLEFEATURELIST = "roleFeatureList"
	self.Paths.CONTROLLER_ROLEFEATUREMODIFY = "roleFeatureModify"
	self.Paths.CONTROLLER_ROLEFEATURES = "roleFeatures"
	self.Paths.CONTROLLER_FEATUREADD = "featureAdd"
	self.Paths.CONTROLLER_FEATURELIST = "featureList"
	self.Paths.CONTROLLER_FEATUREMODIFY = "featureModify"
	self.Paths.CONTROLLER_FEATURES = "features"
	self.Paths.CONTROLLER_APPERRORADD = "appErrorAdd"
	self.Paths.CONTROLLER_APPERRORLIST = "appErrorList"
	self.Paths.CONTROLLER_APPERRORMODIFY = "appErrorModify"
	self.Paths.CONTROLLER_APPERRORS = "appErrors"
	self.Paths.CONTROLLER_TRANSACTIONADD = "transactionAdd"
	self.Paths.CONTROLLER_TRANSACTIONLIST = "transactionList"
	self.Paths.CONTROLLER_TRANSACTIONMODIFY = "transactionModify"
	self.Paths.CONTROLLER_TRANSACTIONS = "login"
	self.Paths.CONTROLLER_HOME = "home"
	self.Paths.CONTROLLER_USERS = "users"
	self.Paths.CONTROLLER_SETTINGS = "settings"
	self.Paths.CONTROLLER_USERLIST = "userList"
	self.Paths.CONTROLLER_SERVERSETTINGSMODIFY = "serverSettingsModify"
	self.Paths.CONTROLLER_USERMODIFY = "userModify"
	self.Paths.CONTROLLER_ACCOUNTMODIFY = "accountModify"
	self.Paths.CONTROLLER_ACCOUNTLIST = "accountList"
	self.Paths.CONTROLLER_ACCOUNTS = "accounts"
	self.Paths.CONTROLLER_PASSWORDRESET = "passwordReset"
	self.Paths.CONTROLLER_USERPROFILE = "userProfile"
	self.Paths.CONTROLLER_USERADD = "userAdd"
	self.Paths.CONTROLLER_ACCOUNTADD = "accountAdd"
}

func (self *RoutesViewModel) Parse(data string) {
	json.Unmarshal([]byte(data), &self)
}
